// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexora.Infra.Persistencia;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexora.Infra.Persistencia.Migrations
{
    [DbContext(typeof(NexoraDbContext))]
    [Migration("20260804101829_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "papel_usuario_enum", new[] { "dono", "gestor", "vendedor" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_usuario_enum", new[] { "ativo", "convidado", "inativo" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexora.Core.Entidades.Empresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Documento")
                        .HasColumnType("text")
                        .HasColumnName("documento");

                    b.Property<string>("FusoHorario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("America/Sao_Paulo")
                        .HasColumnName("fuso_horario");

                    b.Property<short>("JanelaDiasSemana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)126)
                        .HasColumnName("janela_dias_semana");

                    b.Property<short>("JanelaHoraFim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)20)
                        .HasColumnName("janela_hora_fim");

                    b.Property<short>("JanelaHoraInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)8)
                        .HasColumnName("janela_hora_inicio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("empresas", null, t =>
                        {
                            t.HasCheckConstraint("ck_empresas_dias", "janela_dias_semana BETWEEN 1 AND 127");

                            t.HasCheckConstraint("ck_empresas_hora_faixa", "janela_hora_inicio BETWEEN 0 AND 23 AND janela_hora_fim BETWEEN 1 AND 24");

                            t.HasCheckConstraint("ck_empresas_janela", "janela_hora_inicio < janela_hora_fim");
                        });
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_ate");

                    b.Property<DateTime?>("ConviteExpira")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("convite_expira");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<short>("FalhasLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("falhas_login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Papel")
                        .HasColumnType("papel_usuario_enum")
                        .HasColumnName("papel");

                    b.Property<DateTime?>("ResetExpira")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reset_expira");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.Property<int>("Status")
                        .HasColumnType("status_usuario_enum")
                        .HasColumnName("status");

                    b.Property<string>("TokenConvite")
                        .HasColumnType("text")
                        .HasColumnName("token_convite");

                    b.Property<string>("TokenReset")
                        .HasColumnType("text")
                        .HasColumnName("token_reset");

                    b.Property<DateTime?>("UltimoAcessoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acesso_em");

                    b.HasKey("Id");

                    b.HasIndex("TokenConvite")
                        .IsUnique()
                        .HasDatabaseName("uq_usuarios_token_convite")
                        .HasFilter("token_convite IS NOT NULL");

                    b.HasIndex("TokenReset")
                        .IsUnique()
                        .HasDatabaseName("uq_usuarios_token_reset")
                        .HasFilter("token_reset IS NOT NULL");

                    b.HasIndex("EmpresaId", "Status")
                        .HasDatabaseName("ix_usuarios_empresa");

                    b.HasIndex("Id", "EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("uq_usuarios_id_empresa");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuarios_senha", "status = 'convidado' OR senha_hash IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Usuario", b =>
                {
                    b.HasOne("Nexora.Core.Entidades.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Empresa", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
