// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexora.Infra.Persistencia;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexora.Infra.Persistencia.Migrations
{
    [DbContext(typeof(NexoraDbContext))]
    partial class NexoraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "abrangencia_feriado_enum", new[] { "nacional", "estadual", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "direcao_mensagem_enum", new[] { "entrada", "saida" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "origem_lead_enum", new[] { "instagram", "facebook", "whatsapp", "google", "site", "qrcode", "indicacao", "manual", "outro" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "origem_lembrete_enum", new[] { "automatico", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "papel_usuario_enum", new[] { "dono", "gestor", "vendedor" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_conexao_enum", new[] { "nao_criada", "conectando", "conectado", "desconectado", "offline" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_conversa_enum", new[] { "aberta", "resolvida" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_lembrete_enum", new[] { "pendente", "concluido", "cancelado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_usuario_enum", new[] { "ativo", "convidado", "inativo" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_midia_enum", new[] { "nenhum", "imagem", "documento", "audio", "video" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexora.Core.Entidades.Conexao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ConectadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("conectado_em");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DesconectadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("desconectado_em");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instance_name");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<string>("NumeroAnterior")
                        .HasColumnType("text")
                        .HasColumnName("numero_anterior");

                    b.Property<string>("PerfilFotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("perfil_foto_url");

                    b.Property<string>("PerfilNome")
                        .HasColumnType("text")
                        .HasColumnName("perfil_nome");

                    b.Property<int>("Status")
                        .HasColumnType("status_conexao_enum")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StatusEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_em");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "EmpresaId")
                        .HasName("uq_conexoes_id_empresa");

                    b.HasIndex("EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("uq_conexoes_empresa");

                    b.HasIndex("InstanceName")
                        .IsUnique()
                        .HasDatabaseName("uq_conexoes_instance");

                    b.ToTable("conexoes", (string)null);
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Contato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AnonimizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anonimizado_em");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<long>("EtapaId")
                        .HasColumnType("bigint")
                        .HasColumnName("etapa_id");

                    b.Property<DateTime?>("GanhoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ganho_em");

                    b.Property<string>("MotivoPerda")
                        .HasColumnType("text")
                        .HasColumnName("motivo_perda");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<decimal>("OrdemKanban")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("ordem_kanban");

                    b.Property<int>("Origem")
                        .HasColumnType("origem_lead_enum")
                        .HasColumnName("origem");

                    b.Property<string>("OrigemDetalhe")
                        .HasColumnType("text")
                        .HasColumnName("origem_detalhe");

                    b.Property<DateTime?>("PerdidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("perdido_em");

                    b.Property<long?>("ResponsavelId")
                        .HasColumnType("bigint")
                        .HasColumnName("responsavel_id");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "EmpresaId")
                        .HasName("uq_contatos_id_empresa");

                    b.HasIndex("EmpresaId", "CriadoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_contatos_criado");

                    b.HasIndex("EmpresaId", "GanhoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_contatos_ganho")
                        .HasFilter("ganho_em IS NOT NULL");

                    b.HasIndex("EmpresaId", "ResponsavelId")
                        .HasDatabaseName("ix_contatos_responsavel")
                        .HasFilter("responsavel_id IS NOT NULL");

                    b.HasIndex("EmpresaId", "Telefone")
                        .IsUnique()
                        .HasDatabaseName("uq_contatos_telefone")
                        .HasFilter("anonimizado_em IS NULL");

                    b.HasIndex("EmpresaId", "EtapaId", "OrdemKanban")
                        .HasDatabaseName("ix_contatos_kanban")
                        .HasFilter("perdido_em IS NULL");

                    b.ToTable("contatos", null, t =>
                        {
                            t.HasCheckConstraint("ck_contatos_terminal", "ganho_em IS NULL OR perdido_em IS NULL");
                        });
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Conversa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AguardandoDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aguardando_desde");

                    b.Property<DateTime?>("AtribuidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atribuido_em");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("ConexaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("conexao_id");

                    b.Property<long>("ContatoId")
                        .HasColumnType("bigint")
                        .HasColumnName("contato_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<int>("NaoLidas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("nao_lidas");

                    b.Property<DateTime?>("ResolvidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolvido_em");

                    b.Property<long?>("ResolvidoPor")
                        .HasColumnType("bigint")
                        .HasColumnName("resolvido_por");

                    b.Property<long?>("ResponsavelId")
                        .HasColumnType("bigint")
                        .HasColumnName("responsavel_id");

                    b.Property<int>("Status")
                        .HasColumnType("status_conversa_enum")
                        .HasColumnName("status");

                    b.Property<int?>("UltimaMensagemDirecao")
                        .HasColumnType("direcao_mensagem_enum")
                        .HasColumnName("ultima_mensagem_direcao");

                    b.Property<DateTime>("UltimaMensagemEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_mensagem_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UltimaMensagemPrevia")
                        .HasColumnType("text")
                        .HasColumnName("ultima_mensagem_previa");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "EmpresaId")
                        .HasName("uq_conversas_id_empresa");

                    b.HasIndex("ContatoId")
                        .IsUnique()
                        .HasDatabaseName("uq_conversas_contato");

                    b.HasIndex("EmpresaId", "AguardandoDesde")
                        .HasDatabaseName("ix_conversas_aguardando")
                        .HasFilter("aguardando_desde IS NOT NULL");

                    b.HasIndex("EmpresaId", "ResponsavelId", "UltimaMensagemEm")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_conversas_responsavel")
                        .HasFilter("responsavel_id IS NOT NULL");

                    b.HasIndex("EmpresaId", "Status", "UltimaMensagemEm", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_conversas_lista");

                    b.ToTable("conversas", null, t =>
                        {
                            t.HasCheckConstraint("ck_conversas_nao_lidas", "nao_lidas >= 0");
                        });
                });

            modelBuilder.Entity("Nexora.Core.Entidades.EmailEnviado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assunto");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destinatario");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<DateTime>("EnviadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Erro")
                        .HasColumnType("text")
                        .HasColumnName("erro");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("boolean")
                        .HasColumnName("sucesso");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Destinatario", "EnviadoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_emails_destinatario");

                    b.ToTable("emails_enviados", (string)null);
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Empresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Demonstracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("demonstracao");

                    b.Property<short>("DiasSemRespostaFollowUp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2)
                        .HasColumnName("dias_sem_resposta_followup");

                    b.Property<string>("Documento")
                        .HasColumnType("text")
                        .HasColumnName("documento");

                    b.Property<DateTime?>("EquipeDispensadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("equipe_dispensada_em");

                    b.Property<string>("FusoHorario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("America/Sao_Paulo")
                        .HasColumnName("fuso_horario");

                    b.Property<short>("JanelaDiasSemana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)126)
                        .HasColumnName("janela_dias_semana");

                    b.Property<short>("JanelaHoraFim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)20)
                        .HasColumnName("janela_hora_fim");

                    b.Property<short>("JanelaHoraInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)8)
                        .HasColumnName("janela_hora_inicio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<DateTime?>("OnboardingDispensadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onboarding_dispensado_em");

                    b.Property<DateTime?>("PrimeiraMensagemEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("primeira_mensagem_em");

                    b.Property<short>("SemaforoAmareloMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)60)
                        .HasColumnName("semaforo_amarelo_minutos");

                    b.Property<short>("SemaforoVermelhoMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)240)
                        .HasColumnName("semaforo_vermelho_minutos");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("uf")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("empresas", null, t =>
                        {
                            t.HasCheckConstraint("ck_empresas_dias", "janela_dias_semana BETWEEN 1 AND 127");

                            t.HasCheckConstraint("ck_empresas_hora_faixa", "janela_hora_inicio BETWEEN 0 AND 23 AND janela_hora_fim BETWEEN 1 AND 24");

                            t.HasCheckConstraint("ck_empresas_janela", "janela_hora_inicio < janela_hora_fim");
                        });
                });

            modelBuilder.Entity("Nexora.Core.Entidades.EtapaFunil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("#2F5D3A")
                        .HasColumnName("cor");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("EGanho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("e_ganho");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<short>("Ordem")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "EmpresaId")
                        .HasName("uq_etapas_id_empresa");

                    b.HasIndex("EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("uq_etapas_ganho")
                        .HasFilter("e_ganho");

                    b.HasIndex("EmpresaId", "Ordem")
                        .IsUnique()
                        .HasDatabaseName("uq_etapas_ordem");

                    b.ToTable("etapas_funil", (string)null);
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Feriado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("Abrangencia")
                        .HasColumnType("abrangencia_feriado_enum")
                        .HasColumnName("abrangencia");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Uf")
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .HasDatabaseName("ix_feriados_data");

                    b.ToTable("feriados", (string)null);
                });

            modelBuilder.Entity("Nexora.Core.Entidades.FeriadoIgnorado", b =>
                {
                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<long>("FeriadoId")
                        .HasColumnType("bigint")
                        .HasColumnName("feriado_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.HasKey("EmpresaId", "FeriadoId");

                    b.ToTable("feriados_ignorados", (string)null);
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Lembrete", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ConcluidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("concluido_em");

                    b.Property<long?>("ConcluidoPor")
                        .HasColumnType("bigint")
                        .HasColumnName("concluido_por");

                    b.Property<long>("ContatoId")
                        .HasColumnType("bigint")
                        .HasColumnName("contato_id");

                    b.Property<long?>("ConversaId")
                        .HasColumnType("bigint")
                        .HasColumnName("conversa_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("CriadoPor")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por");

                    b.Property<DateOnly>("DataAlvo")
                        .HasColumnType("date")
                        .HasColumnName("data_alvo");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("EnviaMensagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("envia_mensagem");

                    b.Property<TimeOnly?>("HoraAlvo")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_alvo");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<int>("Origem")
                        .HasColumnType("origem_lembrete_enum")
                        .HasColumnName("origem");

                    b.Property<long?>("ResponsavelId")
                        .HasColumnType("bigint")
                        .HasColumnName("responsavel_id");

                    b.Property<int>("Status")
                        .HasColumnType("status_lembrete_enum")
                        .HasColumnName("status");

                    b.Property<string>("TextoMensagem")
                        .HasColumnType("text")
                        .HasColumnName("texto_mensagem");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "EmpresaId")
                        .HasName("uq_lembretes_id_empresa");

                    b.HasIndex("ContatoId", "DataAlvo")
                        .IsUnique()
                        .HasDatabaseName("uq_lembrete_teto_diario")
                        .HasFilter("origem = 'automatico' AND envia_mensagem AND status <> 'cancelado'");

                    b.HasIndex("EmpresaId", "DataAlvo")
                        .HasDatabaseName("ix_lembretes_disparo")
                        .HasFilter("status = 'pendente' AND envia_mensagem");

                    b.HasIndex("EmpresaId", "DataAlvo", "ResponsavelId")
                        .HasDatabaseName("ix_lembretes_dia")
                        .HasFilter("status = 'pendente'");

                    b.ToTable("lembretes", null, t =>
                        {
                            t.HasCheckConstraint("ck_lembretes_texto", "NOT envia_mensagem OR texto_mensagem IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Mensagem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<short?>("Ack")
                        .HasColumnType("smallint")
                        .HasColumnName("ack");

                    b.Property<DateTime?>("AckEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ack_em");

                    b.Property<long>("ConexaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("conexao_id");

                    b.Property<long>("ContatoId")
                        .HasColumnType("bigint")
                        .HasColumnName("contato_id");

                    b.Property<long>("ConversaId")
                        .HasColumnType("bigint")
                        .HasColumnName("conversa_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataDisparo")
                        .HasColumnType("date")
                        .HasColumnName("data_disparo");

                    b.Property<int>("Direcao")
                        .HasColumnType("direcao_mensagem_enum")
                        .HasColumnName("direcao");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<DateTime?>("EnviadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviada_em");

                    b.Property<long?>("EnviadoPor")
                        .HasColumnType("bigint")
                        .HasColumnName("enviado_por");

                    b.Property<string>("Erro")
                        .HasColumnType("text")
                        .HasColumnName("erro");

                    b.Property<DateTime?>("ExpiradaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirada_em");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instance_name");

                    b.Property<long?>("LembreteId")
                        .HasColumnType("bigint")
                        .HasColumnName("lembrete_id");

                    b.Property<int?>("MidiaBytes")
                        .HasColumnType("integer")
                        .HasColumnName("midia_bytes");

                    b.Property<string>("MidiaChave")
                        .HasColumnType("text")
                        .HasColumnName("midia_chave");

                    b.Property<string>("MidiaMime")
                        .HasColumnType("text")
                        .HasColumnName("midia_mime");

                    b.Property<string>("MidiaNome")
                        .HasColumnType("text")
                        .HasColumnName("midia_nome");

                    b.Property<string>("PayloadRaw")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_raw");

                    b.Property<DateTime?>("RecebidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recebida_em");

                    b.Property<DateTime>("ReservadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reservado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Tentativas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("tentativas");

                    b.Property<string>("Texto")
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.Property<int>("TipoMidia")
                        .HasColumnType("tipo_midia_enum")
                        .HasColumnName("tipo_midia");

                    b.Property<string>("WaMessageId")
                        .HasColumnType("text")
                        .HasColumnName("wa_message_id");

                    b.HasKey("Id");

                    b.HasIndex("LembreteId")
                        .IsUnique()
                        .HasDatabaseName("uq_msg_lembrete")
                        .HasFilter("lembrete_id IS NOT NULL");

                    b.HasIndex("EmpresaId", "DataDisparo")
                        .HasDatabaseName("ix_msg_pendentes")
                        .HasFilter("enviada_em IS NULL AND expirada_em IS NULL AND direcao = 'saida'");

                    b.HasIndex("InstanceName", "WaMessageId")
                        .IsUnique()
                        .HasDatabaseName("uq_msg_wa_id")
                        .HasFilter("wa_message_id IS NOT NULL AND wa_message_id <> ''");

                    b.HasIndex("EmpresaId", "ConversaId", "Id")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_msg_timeline");

                    b.ToTable("mensagens", null, t =>
                        {
                            t.HasCheckConstraint("ck_msg_ack", "ack IS NULL OR ack BETWEEN 0 AND 4");

                            t.HasCheckConstraint("ck_msg_data_disparo", "direcao = 'entrada' OR data_disparo IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_ate");

                    b.Property<DateTime?>("ConviteExpira")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("convite_expira");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<short>("FalhasLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("falhas_login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Papel")
                        .HasColumnType("papel_usuario_enum")
                        .HasColumnName("papel");

                    b.Property<DateTime?>("ResetExpira")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reset_expira");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.Property<int>("Status")
                        .HasColumnType("status_usuario_enum")
                        .HasColumnName("status");

                    b.Property<string>("TokenConvite")
                        .HasColumnType("text")
                        .HasColumnName("token_convite");

                    b.Property<string>("TokenReset")
                        .HasColumnType("text")
                        .HasColumnName("token_reset");

                    b.Property<DateTime?>("UltimoAcessoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acesso_em");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "EmpresaId")
                        .HasName("uq_usuarios_id_empresa");

                    b.HasIndex("TokenConvite")
                        .IsUnique()
                        .HasDatabaseName("uq_usuarios_token_convite")
                        .HasFilter("token_convite IS NOT NULL");

                    b.HasIndex("TokenReset")
                        .IsUnique()
                        .HasDatabaseName("uq_usuarios_token_reset")
                        .HasFilter("token_reset IS NOT NULL");

                    b.HasIndex("EmpresaId", "Status")
                        .HasDatabaseName("ix_usuarios_empresa");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuarios_senha", "status = 'convidado' OR senha_hash IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Conexao", b =>
                {
                    b.HasOne("Nexora.Core.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Contato", b =>
                {
                    b.HasOne("Nexora.Core.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexora.Core.Entidades.EtapaFunil", "Etapa")
                        .WithMany()
                        .HasForeignKey("EtapaId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contatos_etapa");

                    b.HasOne("Nexora.Core.Entidades.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contatos_responsavel");

                    b.Navigation("Empresa");

                    b.Navigation("Etapa");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Conversa", b =>
                {
                    b.HasOne("Nexora.Core.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexora.Core.Entidades.Conexao", "Conexao")
                        .WithMany()
                        .HasForeignKey("ConexaoId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversas_conexao");

                    b.HasOne("Nexora.Core.Entidades.Contato", "Contato")
                        .WithMany()
                        .HasForeignKey("ContatoId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversas_contato");

                    b.HasOne("Nexora.Core.Entidades.Usuario", "UsuarioResolveu")
                        .WithMany()
                        .HasForeignKey("ResolvidoPor", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_conversas_resolvido_por");

                    b.HasOne("Nexora.Core.Entidades.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_conversas_responsavel");

                    b.Navigation("Conexao");

                    b.Navigation("Contato");

                    b.Navigation("Empresa");

                    b.Navigation("Responsavel");

                    b.Navigation("UsuarioResolveu");
                });

            modelBuilder.Entity("Nexora.Core.Entidades.EmailEnviado", b =>
                {
                    b.HasOne("Nexora.Core.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Nexora.Core.Entidades.EtapaFunil", b =>
                {
                    b.HasOne("Nexora.Core.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Feriado", b =>
                {
                    b.HasOne("Nexora.Core.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Nexora.Core.Entidades.FeriadoIgnorado", b =>
                {
                    b.HasOne("Nexora.Core.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexora.Core.Entidades.Feriado", "Feriado")
                        .WithMany()
                        .HasForeignKey("FeriadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Feriado");
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Lembrete", b =>
                {
                    b.HasOne("Nexora.Core.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexora.Core.Entidades.Usuario", "UsuarioConcluiu")
                        .WithMany()
                        .HasForeignKey("ConcluidoPor", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lembretes_concluido_por");

                    b.HasOne("Nexora.Core.Entidades.Contato", "Contato")
                        .WithMany()
                        .HasForeignKey("ContatoId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lembretes_contato");

                    b.HasOne("Nexora.Core.Entidades.Conversa", "Conversa")
                        .WithMany()
                        .HasForeignKey("ConversaId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lembretes_conversa");

                    b.HasOne("Nexora.Core.Entidades.Usuario", "UsuarioCriou")
                        .WithMany()
                        .HasForeignKey("CriadoPor", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lembretes_criado_por");

                    b.HasOne("Nexora.Core.Entidades.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lembretes_responsavel");

                    b.Navigation("Contato");

                    b.Navigation("Conversa");

                    b.Navigation("Empresa");

                    b.Navigation("Responsavel");

                    b.Navigation("UsuarioConcluiu");

                    b.Navigation("UsuarioCriou");
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Mensagem", b =>
                {
                    b.HasOne("Nexora.Core.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexora.Core.Entidades.Conexao", "Conexao")
                        .WithMany()
                        .HasForeignKey("ConexaoId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_msg_conexao");

                    b.HasOne("Nexora.Core.Entidades.Contato", "Contato")
                        .WithMany()
                        .HasForeignKey("ContatoId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_msg_contato");

                    b.HasOne("Nexora.Core.Entidades.Conversa", "Conversa")
                        .WithMany()
                        .HasForeignKey("ConversaId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_msg_conversa");

                    b.HasOne("Nexora.Core.Entidades.Usuario", "UsuarioEnviou")
                        .WithMany()
                        .HasForeignKey("EnviadoPor", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_msg_enviado_por");

                    b.HasOne("Nexora.Core.Entidades.Lembrete", "Lembrete")
                        .WithMany()
                        .HasForeignKey("LembreteId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_mensagens_lembrete");

                    b.Navigation("Conexao");

                    b.Navigation("Contato");

                    b.Navigation("Conversa");

                    b.Navigation("Empresa");

                    b.Navigation("Lembrete");

                    b.Navigation("UsuarioEnviou");
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Usuario", b =>
                {
                    b.HasOne("Nexora.Core.Entidades.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Nexora.Core.Entidades.Empresa", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
